Jump to long mode
PragueOS/OS pull request #3
Opened 2023-01-15 15:46 UTC by botondmester

2023-01-15 19:09 UTC, KnedlikMCPE requested changes

2023-01-15 19:09 UTC, KnedlikMCPE commented on kernel/memory/gdt.c
> +};
Missing User Mode segments and Task State Segment

2023-01-15 19:09 UTC, KnedlikMCPE commented on kernel/print.c
> +}
I'm once again asking for _Video memory location_

2023-01-16 16:47 UTC, botondmester commented on kernel/memory/gdt.c
> +};
We will add that later

2023-01-16 16:48 UTC, KnedlikMCPE commented on kernel/memory/gdta.asm
> +        mov ax, [ebp + 16]
16-bit registers

2023-01-16 16:48 UTC, botondmester commented on kernel/print.c
> +}
Comment added, but not commited yet, check discord

2023-01-16 16:48 UTC, merged